# 🧠 PyTorch Basics

This notebook provides a comprehensive introduction to **PyTorch**, covering essential topics, theory, functions, and practical examples. It's designed to help you understand the PyTorch framework for deep learning.

📘 **Official Documentation**: [https://pytorch.org/docs/stable/index.html](https://pytorch.org/docs/stable/index.html)

📘 **Official Pytorch Cheatsheet**: [https://docs.pytorch.org/tutorials/beginner/ptcheat.html](https://docs.pytorch.org/tutorials/beginner/ptcheat.html)


---

## 📑 Contents
1. What is PyTorch?
2. Tensors in PyTorch
3. Tensor Operations
4. Indexing and Slicing
4. Autograd / Gradients
5. Loss Functions
6. Optimization
7. Neural Network Modules
8. GPU Acceleration with CUDA
9. Saving and Loading Models
10. Summary


## 1. What is PyTorch?

**PyTorch** is an open-source machine learning library developed by Facebook AI. It's widely used for deep learning applications such as computer vision and natural language processing.

- Tensor-based computation (like NumPy but with GPU support)
- Dynamic computational graph
- Powerful autograd engine
- Supports CUDA for GPU acceleration



## 2. Tensor Creation Functions

Tensors are the core data structure of PyTorch, similar to NumPy arrays but with GPU acceleration.



| Function           | Usage Description                             | Example                        |
| ------------------ | --------------------------------------------- | ------------------------------ |
| `torch.tensor()`   | Creates a tensor from data                    | `torch.tensor([1, 2, 3])`      |
| `torch.zeros()`    | Creates a tensor filled with zeros            | `torch.zeros(2, 3)`            |
| `torch.ones()`     | Creates a tensor filled with ones             | `torch.ones(3, 2)`             |
| `torch.arange()`   | Returns evenly spaced values                  | `torch.arange(0, 10, 2)`       |
| `torch.linspace()` | Returns values spaced evenly over an interval | `torch.linspace(0, 1, 5)`      |
| `torch.rand()`     | Uniform random values in \[0,1)               | `torch.rand(2, 2)`             |
| `torch.randn()`    | Normal distribution values                    | `torch.randn(2, 2)`            |
| `torch.randint()`  | Random ints from range                        | `torch.randint(0, 10, (2, 3))` |
| `torch.eye()`      | Identity matrix                               | `torch.eye(3)`                 |
| `torch.empty()`    | Uninitialized values (memory garbage)         | `torch.empty(2, 2)`            |

These functions initialize tensors with specific values or patterns.

In [1]:
import torch

# From data
data = [[1, 2], [3, 4]]
x_data = torch.tensor(data)
print(x_data)

# From NumPy array
import numpy as np
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)

# With random or constant values
x_ones = torch.ones_like(x_data)
x_rand = torch.rand_like(x_data, dtype=torch.float)
print(x_ones)
print(x_rand)

# With specific shape
shape = (2, 3,)
rand_tensor = torch.rand(shape)
ones_tensor = torch.ones(shape)
zeros_tensor = torch.zeros(shape)
print(rand_tensor)
print(ones_tensor)
print(zeros_tensor)

tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]], dtype=torch.int32)
tensor([[1, 1],
        [1, 1]])
tensor([[0.6961, 0.6508],
        [0.8906, 0.5505]])
tensor([[0.7404, 0.5891, 0.6816],
        [0.6025, 0.9174, 0.5807]])
tensor([[1., 1., 1.],
        [1., 1., 1.]])
tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [3]:
import torch

print("Tensor from list:", torch.tensor([1, 2, 3]))
print("Zeros:", torch.zeros(2, 2))
print("Ones:", torch.ones(2, 2))
print("Arange:", torch.arange(0, 10, 2))
print("Linspace:", torch.linspace(0, 1, 5))
print("Rand:", torch.rand(2, 2))
print("Randn:", torch.randn(2, 2))
print("Randint:", torch.randint(0, 10, (2, 2)))
print("Eye:", torch.eye(3))
print("Empty:", torch.empty(2, 2))

Tensor from list: tensor([1, 2, 3])
Zeros: tensor([[0., 0.],
        [0., 0.]])
Ones: tensor([[1., 1.],
        [1., 1.]])
Arange: tensor([0, 2, 4, 6, 8])
Linspace: tensor([0.0000, 0.2500, 0.5000, 0.7500, 1.0000])
Rand: tensor([[0.7182, 0.5519],
        [0.4947, 0.1440]])
Randn: tensor([[ 1.5066, -0.7911],
        [ 0.7500, -0.0727]])
Randint: tensor([[4, 9],
        [3, 9]])
Eye: tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Empty: tensor([[ 0.0000, 18.9802],
        [ 0.0000,  0.0000]])


## 3. Tensor Operations

PyTorch supports a wide range of tensor operations similar to NumPy.

| Function            | Usage Description               | Example                      |
| ------------------- | ------------------------------- | ---------------------------- |
| `torch.add()`       | Element-wise addition           | `torch.add(t1, t2)`          |
| `torch.sub()`       | Element-wise subtraction        | `torch.sub(t1, t2)`          |
| `torch.mul()`       | Element-wise multiplication     | `torch.mul(t1, t2)`          |
| `torch.div()`       | Element-wise division           | `torch.div(t1, t2)`          |
| `torch.matmul()`    | Matrix multiplication           | `torch.matmul(t1, t2)`       |
| `torch.mm()`        | Matrix multiplication (2D only) | `torch.mm(t1, t2)`           |
| `torch.t()`         | Transpose 2D tensor             | `torch.t(t)`                 |
| `torch.view()`      | Reshape tensor                  | `t.view(2, 6)`               |
| `torch.reshape()`   | Reshape tensor                  | `t.reshape(3, 2)`            |
| `torch.squeeze()`   | Remove dimensions of size 1     | `t.squeeze()`                |
| `torch.unsqueeze()` | Add a dimension                 | `t.unsqueeze(0)`             |
| `torch.cat()`       | Concatenate tensors             | `torch.cat((t1, t2), dim=0)` |
| `torch.stack()`     | Stack tensors along new dim     | `torch.stack((t1, t2))`      |


### Examples:

In [4]:
# Addition
x = torch.rand(2, 2)
y = torch.rand(2, 2)
z = x + y
print(z)

# Multiplication
z = x * y
print(z)

# Matrix multiplication
z = torch.matmul(x, y)
print(z)

# In-place operations
y.add_(x)
print(y)

tensor([[1.5275, 1.0413],
        [0.4973, 1.1403]])
tensor([[0.5325, 0.2468],
        [0.0362, 0.2164]])
tensor([[0.5924, 0.8052],
        [0.4257, 0.3655]])
tensor([[1.5275, 1.0413],
        [0.4973, 1.1403]])


In [5]:
a = torch.tensor([[1, 2], [3, 4]])
b = torch.tensor([[5, 6], [7, 8]])

print("Add:", torch.add(a, b))
print("Sub:", torch.sub(a, b))
print("Mul:", torch.mul(a, b))
print("Div:", torch.div(a, b))
print("Matmul:", torch.matmul(a, b))
print("View (reshape):", a.view(4))
print("Squeeze:", torch.tensor([[[1]]]).squeeze())
print("Unsqueeze:", torch.tensor([1, 2]).unsqueeze(0))

Add: tensor([[ 6,  8],
        [10, 12]])
Sub: tensor([[-4, -4],
        [-4, -4]])
Mul: tensor([[ 5, 12],
        [21, 32]])
Div: tensor([[0.2000, 0.3333],
        [0.4286, 0.5000]])
Matmul: tensor([[19, 22],
        [43, 50]])
View (reshape): tensor([1, 2, 3, 4])
Squeeze: tensor(1)
Unsqueeze: tensor([[1, 2]])


## 4. Indexing & Slicing

Used to access elements or slices of tensors.

| Function                | Usage Description         | Example                            |
| ----------------------- | ------------------------- | ---------------------------------- |
| `tensor[index]`         | Standard indexing         | `t[0]`, `t[:, 1]`                  |
| `tensor[:], tensor[::]` | Slicing syntax            | `t[1:3]`                           |
| `torch.gather()`        | Gather values along axis  | `torch.gather(t, 1, index_tensor)` |
| `torch.masked_select()` | Select using boolean mask | `torch.masked_select(t, mask)`     |


In [6]:
t = torch.tensor([[1, 2, 3], [4, 5, 6]])
print("Indexing:", t[1, 2])
print("Slicing:", t[:, 1:])

Indexing: tensor(6)
Slicing: tensor([[2, 3],
        [5, 6]])


## 5. Autograd / Gradients

PyTorch uses autograd for automatic differentiation, essential for training neural networks.

| Function                | Usage Description                     | Example                              |
| ----------------------- | ------------------------------------- | ------------------------------------ |
| `.requires_grad_()`     | Enable gradient tracking              | `t.requires_grad_()`                 |
| `.backward()`           | Compute gradients                     | `loss.backward()`                    |
| `.grad`                 | Access gradients                      | `t.grad`                             |
| `torch.autograd.grad()` | Compute and return gradients manually | `torch.autograd.grad(output, input)` |
| `torch.no_grad()`       | Disable gradient tracking             | `with torch.no_grad(): ...`          |


In [7]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

y = x + 2
z = y * y * 3
out = z.mean()
print(out)

# Backprop
out.backward()
print(x.grad)  # d(out)/dx

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
tensor(27., grad_fn=<MeanBackward0>)
tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [8]:
x = torch.tensor(2.0, requires_grad=True)
y = x**2
y.backward()
print("Gradient of x**2 w.r.t x:", x.grad)

Gradient of x**2 w.r.t x: tensor(4.)


## 6. Loss Functions

Measure difference between prediction and target.

| Function                      | Usage Description              | Example                               |
| ----------------------------- | ------------------------------ | ------------------------------------- |
| `torch.nn.MSELoss()`          | Mean squared error loss        | `loss = MSELoss()(pred, target)`      |
| `torch.nn.CrossEntropyLoss()` | For multi-class classification | `loss = CrossEntropyLoss()(out, lbl)` |
| `torch.nn.BCELoss()`          | Binary cross entropy           | `loss = BCELoss()(out, lbl)`          |
| `F.nll_loss()`                | Negative log likelihood        | `F.nll_loss(pred, target)`            |


In [9]:
import torch.nn as nn
loss_fn = nn.MSELoss()
pred = torch.tensor([1.0, 2.0], requires_grad=True)
target = torch.tensor([1.5, 2.5])
loss = loss_fn(pred, target)
print("MSE Loss:", loss.item())

MSE Loss: 0.25


## 7. Optimization

Update model weights using gradients.

| Function           | Usage Description                   | Example                                        |
| ------------------ | ----------------------------------- | ---------------------------------------------- |
| `torch.optim.SGD`  | Stochastic gradient descent         | `optimizer = SGD(model.parameters(), lr=0.01)` |
| `torch.optim.Adam` | Adam optimizer                      | `optimizer = Adam(model.parameters())`         |
| `.step()`          | Perform optimization step           | `optimizer.step()`                             |
| `.zero_grad()`     | Zero gradients before backward pass | `optimizer.zero_grad()`                        |


In [10]:
model = nn.Linear(2, 1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01)
input = torch.tensor([[1.0, 2.0]])
target = torch.tensor([[1.0]])
output = model(input)
loss = loss_fn(output, target)
loss.backward()
optimizer.step()
optimizer.zero_grad()

## 8. Neural Network Modules

PyTorch provides some modules to build neural networks.

| Function                | Usage Description         | Example                              |
| ----------------------- | ------------------------- | ------------------------------------ |
| `torch.nn.Linear()`     | Fully connected layer     | `nn.Linear(128, 64)`                 |
| `torch.nn.Conv2d()`     | Convolutional layer       | `nn.Conv2d(1, 16, 3)`                |
| `torch.nn.ReLU()`       | ReLU activation           | `nn.ReLU()`                          |
| `torch.nn.Sigmoid()`    | Sigmoid activation        | `nn.Sigmoid()`                       |
| `torch.nn.Sequential()` | Stack layers sequentially | `nn.Sequential(nn.Linear(...), ...)` |



In [11]:
model = nn.Sequential(
    nn.Linear(4, 3),
    nn.ReLU(),
    nn.Linear(3, 1)
)
print("Model architecture:", model)

Model architecture: Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


In [12]:
import torch.nn as nn
import torch.nn.functional as F

class Net(nn.Module):
    def __init__(self):
        super(Net, self).__init__()
        self.fc1 = nn.Linear(784, 128)
        self.fc2 = nn.Linear(128, 10)

    def forward(self, x):
        x = F.relu(self.fc1(x))
        return self.fc2(x)

net = Net()
print(net)

Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)


## 6. GPU Acceleration with CUDA

Manage computation on CPU or GPU

| Function                    | Usage Description              | Example                         |
| --------------------------- | ------------------------------ | ------------------------------- |
| `torch.device()`            | Define device                  | `device = torch.device("cuda")` |
| `.to(device)`               | Move tensor or model to device | `model.to(device)`              |
| `torch.cuda.is_available()` | Check for GPU availability     | `torch.cuda.is_available()`     |


In [13]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Using device:", device)

x = torch.rand(5, 5).to(device)
y = torch.rand(5, 5).to(device)
z = x + y
print("Tensor device:", z.device)

Using device: cuda
Tensor device: cuda:0


## 7. Saving and Loading Models

Save and reload model weights.

| Function             | Usage Description            | Example                                       |
| -------------------- | ---------------------------- | --------------------------------------------- |
| `torch.save()`       | Save tensor or model         | `torch.save(model.state_dict(), "model.pth")` |
| `torch.load()`       | Load tensor or model         | `state_dict = torch.load("model.pth")`        |
| `.load_state_dict()` | Load into model architecture | `model.load_state_dict(state_dict)`           |
| `.eval()`            | Set model to evaluation mode | `model.eval()`                                |
| `.train()`           | Set model to training mode   | `model.train()`                               |




In [14]:

# Save model
torch.save(net.state_dict(), 'model.pth')

# Load model
model = Net()
model.load_state_dict(torch.load('model.pth'))
model.eval()

Net(
  (fc1): Linear(in_features=784, out_features=128, bias=True)
  (fc2): Linear(in_features=128, out_features=10, bias=True)
)

## 8. Summary

- PyTorch is a powerful deep learning library
- Core concept: Tensors
- Supports autograd, GPU acceleration, and model training
- Modular design: tensors, autograd, nn, optim

---